import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "../layout.module.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <header className={styles.header}>
        <h1>분류</h1>
        <nav className={styles.nav}>
          <a href="/about/woman">여성옷</a>
          <a href="/about/man">남성옷</a>
        </nav>
      </header>
      {children}
    </div>
  );
}
